### ISSUE TITLE
Syntax sugar to define elements on a page

### ISSUE THREAD

**Issue by rubemz** [andyw8/capybara-page-object#2]
Would be nice to declare an element like in this gist: https://gist.github.com/2411979

**Comment by andyw8** [comment]
Note that you still need _source.find_button_ rather than just _find_button_. I'm planning to improve this.

**Comment by rubemz** [comment]
Cool! Thanks :)

On Thu, Apr 19, 2012 at 3:32 AM, Andy Waite <
reply@reply.github.com

> wrote:
> 
> Note that you still need _source.find_button_ rather than just
> _find_button_. I'm planning to improve this.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/andyw8/capybara-page-object/issues/2#issuecomment-5209928

## 

Rubem Nakamura
