### ISSUE TITLE
Semver broken on 0.6.1

### ISSUE THREAD

**Issue by tanob** [andyw8/capybara-page-object#5]
Please consider following semantic versioning (semver.org) for the API. There was a public method renamed and released in a patch version (0.6.0 -> 0.6.1):
https://github.com/andyw8/capybara-page-object/commit/3ef5da87fa13d9bc2d995c8ba94a40ca88a92616

Thanks

**Comment by andyw8** [comment]
Sorry, my bad. Will aim to improve that in future.
